environment:
  matrix:
  - TARGET: i686-pc-windows-msvc
    OTHER_TARGET: x86_64-pc-windows-msvc
    MSVC: 1
    BITS: 32
    ARCH: x86
  - TARGET: x86_64-pc-windows-msvc
    OTHER_TARGET: i686-pc-windows-msvc
    MSVC: 1
    BITS: 64
    ARCH: amd64
  - TARGET: x86_64-pc-windows-gnu
    ARCH: amd64
    BITS: 64
    CFG_DISABLE_CROSS_TESTS: 1
  - TARGET: i686-pc-windows-gnu
    ARCH: x86
    BITS: 32
    MINGW_ARCHIVE: i686-4.9.2-release-win32-dwarf-rt_v4-rev4.7z
    MINGW_URL: https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/4.9.2/threads-win32/dwarf/i686-4.9.2-release-win32-dwarf-rt_v4-rev4.7z/download
    MINGW_DIR: mingw32
    CFG_DISABLE_CROSS_TESTS: 1

install:
  - if "%MSVC%"=="" set PATH=C:\msys64\mingw%BITS%\bin;C:\msys64\usr\bin;%PATH%
  - if defined MINGW_ARCHIVE appveyor DownloadFile "%MINGW_URL%" -FileName "%MINGW_ARCHIVE%"
  - if defined MINGW_ARCHIVE 7z x -y "%MINGW_ARCHIVE%" > nul
  - if defined MINGW_ARCHIVE set PATH=%CD%\%MINGW_DIR%\bin;C:\msys64\usr\bin;%PATH%
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - if defined OTHER_TARGET rustup target add %OTHER_TARGET%
  - rustc -V
  - cargo -V

build: false

test_script:
  - cargo test
